### ISSUE TITLE
You and your repo should be easier to find.

### ISSUE THREAD

**Issue by nedbat** [gfxmonk/rednose#27]
The PyPI page for rednose has no author name, and no link to a source repository.
It has a link to http://gfxmonk.net/dist/0install/rednose.xml, which also as no author name or repo link (it took me a while to realize the entire site was your personal site).

**Comment by gfxmonk** [comment]
Fair point - I've added a homepage link in the feed and changed the pypi URL to take you directly to github. I'm hoping that's sufficient (I would populate author info, but it's generated from rednose.xml which doesn't have that info)
